Support 'alias' for QMpsApplication's key
task-jp/qtmultiprocesssystem pull request #5
Opened 2022-05-27 01:45 UTC by tkhshmsy

- it registers duplicate applications with replacing its key.

2022-05-27 02:21 UTC, task-jp requested changes

2022-05-27 02:21 UTC, task-jp commented on src/multiprocesssystem/qmpsapplication.cpp
>      QMpsApplication ret;
QMpsApplication app;

2022-05-27 02:21 UTC, task-jp commented on src/multiprocesssystem/qmpsapplication.cpp
> +    QList<QMpsApplication> rets;
QList<QMpsApplication> ret;

2022-05-27 02:21 UTC, task-jp commented on src/multiprocesssystem/qmpsapplication.cpp
> +    if (json.contains(QStringLiteral("alias"))) {
alias があったら、key に加えてそれらも追加する感じ？

2022-05-27 02:43 UTC, tkhshmsy commented on src/multiprocesssystem/qmpsapplication.cpp
> +    if (json.contains(QStringLiteral("alias"))) {
そういうイメージ。
・key を alias のもののに差し替える(＝登録アプリケーションが増える)
・起動するものは key のものと同じにしたいので role を追加した

2022-05-27 04:59 UTC, task-jp commented on src/multiprocesssystem/qmpsapplication.cpp
> +    if (json.contains(QStringLiteral("alias"))) {
特殊なケース（alias があるもの）以外は key == role なのが無駄な気がする。
例えばだけど、role を qml に名前変えて、実行ファイルを指定できるようにするというのはどうかしら。

2022-05-28 04:02 UTC, tkhshmsy commented on src/multiprocesssystem/qmpsapplication.cpp
> +    if (json.contains(QStringLiteral("alias"))) {
読み込むqmlを指定できるのはそれはそれで良さそうとは思うけど、
QMpsApplicationFactory::load() に渡す引数の作成に結局 role に相当するものが欲しくなるんだよね

2022-05-30 01:23 UTC, task-jp commented on src/multiprocesssystem/qmpsapplication.cpp
> +    if (json.contains(QStringLiteral("alias"))) {
とりあえずこれで先に進もうか

2022-05-30 01:25 UTC, merged